export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const HANDLE_DIRECTION = 'HANDLE_DIRECTION';

export const LINK_CLICKED = 'LINK_CLICKED';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const TOGGLE_SIDEDRAWER = 'TOGGLE_SIDEDRAWER';