// PRODUCT REDUCER
// filter products by category
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';

// handle sort utilities in ProductList component
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const HANDLE_DIRECTION = 'HANDLE_DIRECTION';
export const HANDLE_CHECKBOX_VALUE = 'HANDLE_CHECKBOX_VALUE';

export const SHOW_DETAILS = 'SHOW_DETAILS';

export const CALCULATE_ORDER = 'CALCULATE_ORDER';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const HANDLE_PRODUCT_AMOUNT = 'HANDLE_PRODUCT_AMOUNT';
export const CLEAR_CART = 'CLEAR_CART';

export const REMOVE_WISHLIST_ITEM = 'REMOVE_WISHLIST_ITEM';
export const CLEAR_WISHLIST = 'CLEAR_WISHLIST';

// INTERFACE REDUCER
export const LINK_CLICKED = 'LINK_CLICKED';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const TOGGLE_SIDEDRAWER = 'TOGGLE_SIDEDRAWER';